---
- name: Bootstrap Root Password and SSH Keys on Proxmox LXCs
  hosts: tag_deploy
  gather_facts: false

  connection: community.proxmox.proxmox_pct_remote

  vars:
    ansible_host: "192.168.1.114"
    ansible_user: "root"
    proxmox_node: "pve1"

  tasks:
    - name: Update root user password inside container
      ansible.builtin.user:
        name: root
        password: "{{ hash }}"

    - name: Ensure SSH public keys are present in root's authorized_keys
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ ssh_public_keys }}"

    - name: Remove 'deploy' tag from container
      ansible.builtin.command: >
        pvesh set /nodes/{{ proxmox_node }}/lxc/{{ inventory_hostname }}/config --tags ""
